version: 2.1

orbs:
  ruby: circleci/ruby@2.1.1
  codecov: codecov/codecov@4.0.1

jobs:
  build-and-test:
    docker:
      - image: cimg/ruby:3.2.2

    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/install-deps
      - run:
          name: Run Tests
          command: bundle exec rspec
      - codecov/upload

workflows:
  build-and-test:
    jobs:
      - build
